compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-4.3.0.cjs

packageExtensions:
  "@preact/preset-vite@*":
    dependencies:
      "@babel/code-frame": "*"
