Activities.remove({});

const activities = [
    { name: 'Aerobics', googleFitType: 9 },
    { name: 'Badminton', googleFitType: 10 },
    { name: 'Baseball', googleFitType: 11 },
    { name: 'Basketball', googleFitType: 12 },
    { name: 'Biathlon', googleFitType: 13 },
    { name: 'Biking', googleFitType: 1 },
    { name: 'Handbiking', googleFitType: 14 },
    { name: 'Mountain biking', googleFitType: 15 },
    { name: 'Road biking', googleFitType: 16 },
    { name: 'Spinning', googleFitType: 17 },
    { name: 'Stationary biking', googleFitType: 18 },
    { name: 'Utility biking', googleFitType: 19 },
    { name: 'Boxing', googleFitType: 20 },
    { name: 'Calisthenics', googleFitType: 21 },
    { name: 'Circuit training', googleFitType: 22 },
    { name: 'Cricket', googleFitType: 23 },
    { name: 'Curling', googleFitType: 106 },
    { name: 'Dancing', googleFitType: 24 },
    { name: 'Diving', googleFitType: 102 },
    { name: 'Elliptical', googleFitType: 25 },
    { name: 'Ergometer', googleFitType: 103 },
    { name: 'Fencing', googleFitType: 26 },
    { name: 'Football (American)', googleFitType: 27 },
    { name: 'Football (Australian)', googleFitType: 28 },
    { name: 'Football (Soccer)', googleFitType: 29 },
    { name: 'Frisbee', googleFitType: 30 },
    { name: 'Gardening', googleFitType: 31 },
    { name: 'Golf', googleFitType: 32 },
    { name: 'Gymnastics', googleFitType: 33 },
    { name: 'Handball', googleFitType: 34 },
    { name: 'Hiking', googleFitType: 35 },
    { name: 'Hockey', googleFitType: 36 },
    { name: 'Horseback riding', googleFitType: 37 },
    { name: 'Housework', googleFitType: 38 },
    { name: 'Ice skating', googleFitType: 104 },
    { name: 'In vehicle', googleFitType: 0 },
    { name: 'Jumping rope', googleFitType: 39 },
    { name: 'Kayaking', googleFitType: 40 },
    { name: 'Kettlebell training', googleFitType: 41 },
    { name: 'Kickboxing', googleFitType: 42 },
    { name: 'Kitesurfing', googleFitType: 43 },
    { name: 'Martial arts', googleFitType: 44 },
    { name: 'Meditation', googleFitType: 45 },
    { name: 'Mixed martial arts', googleFitType: 46 },
    { name: 'On foot', googleFitType: 2 },
    { name: 'Other (unclassified fitness activity)', googleFitType: 108 },
    { name: 'P90X exercises', googleFitType: 47 },
    { name: 'Paragliding', googleFitType: 48 },
    { name: 'Pilates', googleFitType: 49 },
    { name: 'Polo', googleFitType: 50 },
    { name: 'Racquetball', googleFitType: 51 },
    { name: 'Rock climbing', googleFitType: 52 },
    { name: 'Rowing', googleFitType: 53 },
    { name: 'Rowing machine', googleFitType: 54 },
    { name: 'Rugby', googleFitType: 55 },
    { name: 'Running', googleFitType: 8 },
    { name: 'Jogging', googleFitType: 56 },
    { name: 'Running on sand', googleFitType: 57 },
    { name: 'Running (treadmill)', googleFitType: 58 },
    { name: 'Sailing', googleFitType: 59 },
    { name: 'Scuba diving', googleFitType: 60 },
    { name: 'Skateboarding', googleFitType: 61 },
    { name: 'Skating', googleFitType: 62 },
    { name: 'Cross skating', googleFitType: 63 },
    { name: 'Indoor skating', googleFitType: 105 },
    { name: 'Inline skating (rollerblading)', googleFitType: 64 },
    { name: 'Skiing', googleFitType: 65 },
    { name: 'Back-country skiing', googleFitType: 66 },
    { name: 'Cross-country skiing', googleFitType: 67 },
    { name: 'Downhill skiing', googleFitType: 68 },
    { name: 'Kite skiing', googleFitType: 69 },
    { name: 'Roller skiing', googleFitType: 70 },
    { name: 'Sledding', googleFitType: 71 },
    { name: 'Sleeping', googleFitType: 72 },
    { name: 'Light sleep', googleFitType: 109 },
    { name: 'Deep sleep', googleFitType: 110 },
    { name: 'REM sleep', googleFitType: 111 },
    { name: 'Awake (during sleep cycle)', googleFitType: 112 },
    { name: 'Snowboarding', googleFitType: 73 },
    { name: 'Snowmobile', googleFitType: 74 },
    { name: 'Snowshoeing', googleFitType: 75 },
    { name: 'Squash', googleFitType: 76 },
    { name: 'Stair climbing', googleFitType: 77 },
    { name: 'Stair-climbing machine', googleFitType: 78 },
    { name: 'Stand-up paddleboarding', googleFitType: 79 },
    { name: 'Still (not moving)', googleFitType: 3 },
    { name: 'Strength training', googleFitType: 80 },
    { name: 'Surfing', googleFitType: 81 },
    { name: 'Swimming', googleFitType: 82 },
    { name: 'Swimming (open water)', googleFitType: 84 },
    { name: 'Swimming (swimming pool)', googleFitType: 83 },
    { name: 'Table tennis (ping pong)', googleFitType: 85 },
    { name: 'Team sports', googleFitType: 86 },
    { name: 'Tennis', googleFitType: 87 },
    { name: 'Tilting (sudden device gravity change)', googleFitType: 5 },
    { name: 'Treadmill (walking or running)', googleFitType: 88 },
    { name: 'Unknown (unable to detect activity)', googleFitType: 4 },
    { name: 'Volleyball', googleFitType: 89 },
    { name: 'Volleyball (beach)', googleFitType: 90 },
    { name: 'Volleyball (indoor)', googleFitType: 91 },
    { name: 'Wakeboarding', googleFitType: 92 },
    { name: 'Walking', googleFitType: 7 },
    { name: 'Walking (fitness)', googleFitType: 93 },
    { name: 'Nording walking', googleFitType: 94 },
    { name: 'Walking (treadmill)', googleFitType: 95 },
    { name: 'Waterpolo', googleFitType: 96 },
    { name: 'Weightlifting', googleFitType: 97 },
    { name: 'Wheelchair', googleFitType: 98 },
    { name: 'Windsurfing', googleFitType: 99 },
    { name: 'Yoga', googleFitType: 100 },
    { name: 'Zumba', googleFitType: 101 }
];

activities.forEach((activity) => {
    Activities.insert(activity);
});
