const activities = [
    { name: 'archery' },
    { name: 'aerobics', googleFitType: 9 },
    { name: 'badminton', googleFitType: 10 },
    { name: 'baseball', googleFitType: 11 },
    { name: 'basketball', googleFitType: 12 },
    { name: 'biathlon', googleFitType: 13 },
    { name: 'biking', googleFitType: 1 },
    { name: 'bowling' },
    { name: 'handbiking', googleFitType: 14 },
    { name: 'mountain_biking', googleFitType: 15 },
    { name: 'road_biking', googleFitType: 16 },
    { name: 'spinning', googleFitType: 17 },
    { name: 'stationary_biking', googleFitType: 18 },
    { name: 'utility_biking', googleFitType: 19 },
    { name: 'boxing', googleFitType: 20 },
    { name: 'calisthenics', googleFitType: 21 },
    { name: 'circuit_training', googleFitType: 22 },
    { name: 'cricket', googleFitType: 23 },
    { name: 'curling', googleFitType: 106 },
    { name: 'dancing', googleFitType: 24 },
    { name: 'darts' },
    { name: 'diving', googleFitType: 102 },
    { name: 'elliptical', googleFitType: 25 },
    { name: 'ergometer', googleFitType: 103 },
    { name: 'fencing', googleFitType: 26 },
    { name: 'american_football', googleFitType: 27 },
    { name: 'australian_football', googleFitType: 28 },
    { name: 'soccer', googleFitType: 29 },
    { name: 'frisbee', googleFitType: 30 },
    { name: 'gardening', googleFitType: 31 },
    { name: 'golf', googleFitType: 32 },
    { name: 'gymnastics', googleFitType: 33 },
    { name: 'handball', googleFitType: 34 },
    { name: 'hiking', googleFitType: 35 },
    { name: 'hockey', googleFitType: 36 },
    { name: 'horseback_riding', googleFitType: 37 },
    { name: 'housework', googleFitType: 38 },
    { name: 'ice_skating', googleFitType: 104 },
    { name: 'jumping_rope', googleFitType: 39 },
    { name: 'kayaking', googleFitType: 40 },
    { name: 'kettlebell', googleFitType: 41 },
    { name: 'kickboxing', googleFitType: 42 },
    { name: 'kitesurfing', googleFitType: 43 },
    { name: 'martial_arts', googleFitType: 44 },
    { name: 'meditation', googleFitType: 45 },
    { name: 'mixed_martial_arts', googleFitType: 46 },
    { name: 'p90x_exercises', googleFitType: 47 },
    { name: 'paragliding', googleFitType: 48 },
    { name: 'pilates', googleFitType: 49 },
    { name: 'polo', googleFitType: 50 },
    { name: 'racquetball', googleFitType: 51 },
    { name: 'rock climbing', googleFitType: 52 },
    { name: 'rowing', googleFitType: 53 },
    { name: 'rowing_machine', googleFitType: 54 },
    { name: 'rugby', googleFitType: 55 },
    { name: 'running', googleFitType: 8 },
    { name: 'jogging', googleFitType: 56 },
    { name: 'running_on_sand', googleFitType: 57 },
    { name: 'running_on_treadmill', googleFitType: 58 },
    { name: 'sailing', googleFitType: 59 },
    { name: 'scuba_diving', googleFitType: 60 },
    { name: 'skateboarding', googleFitType: 61 },
    { name: 'skating', googleFitType: 62 },
    { name: 'cross_skating', googleFitType: 63 },
    { name: 'indoor_skating', googleFitType: 105 },
    { name: 'rollerblading', googleFitType: 64 },
    { name: 'skiing', googleFitType: 65 },
    { name: 'back-country_skiing', googleFitType: 66 },
    { name: 'cross-country_skiing', googleFitType: 67 },
    { name: 'downhill_skiing', googleFitType: 68 },
    { name: 'kite_skiing', googleFitType: 69 },
    { name: 'pool' },
    { name: 'racing' },
    { name: 'roller_skiing', googleFitType: 70 },
    { name: 'sledding', googleFitType: 71 },
    { name: 'snowboarding', googleFitType: 73 },
    { name: 'snowmobile', googleFitType: 74 },
    { name: 'snowshoeing', googleFitType: 75 },
    { name: 'squash', googleFitType: 76 },
    { name: 'stair_climbing', googleFitType: 77 },
    { name: 'stair-climbing_machine', googleFitType: 78 },
    { name: 'stand-up_paddleboarding', googleFitType: 79 },
    { name: 'strength_training', googleFitType: 80 },
    { name: 'surfing', googleFitType: 81 },
    { name: 'swimming', googleFitType: 82 },
    { name: 'swimming_outside', googleFitType: 84 },
    { name: 'swimming_pool', googleFitType: 83 },
    { name: 'table_tennis', googleFitType: 85 },
    { name: 'team sports', googleFitType: 86 },
    { name: 'tennis', googleFitType: 87 },
    { name: 'treadmill', googleFitType: 88 },
    { name: 'volleyball', googleFitType: 89 },
    { name: 'volleyball_beach', googleFitType: 90 },
    { name: 'volleyball_indoor', googleFitType: 91 },
    { name: 'wakeboarding', googleFitType: 92 },
    { name: 'walking', googleFitType: 7 },
    { name: 'walking_fitness', googleFitType: 93 },
    { name: 'nording_walking', googleFitType: 94 },
    { name: 'walking_treadmill', googleFitType: 95 },
    { name: 'waterpolo', googleFitType: 96 },
    { name: 'weightlifting', googleFitType: 97 },
    { name: 'wheelchair', googleFitType: 98 },
    { name: 'windsurfing', googleFitType: 99 },
    { name: 'yoga', googleFitType: 100 },
    { name: 'zumba', googleFitType: 101 }
];

activities.forEach((activity) => {
    Activities.update(
        { name: activity.name },
        activity,
        { upsert: true }
    );
});
