main = "./src/index.js"
compatibility_date = "2022-09-06"

[env.dev]
name = "upload-url-dev"

[env.dev.vars]
ALLOWED_ORIGIN = "http://localhost:8080"

[env.production]
name = "upload-url"

[env.production.vars]
ALLOWED_ORIGIN = "https://chealt.com"

# The necessary secrets are:
# - ACCOUNT_ID
# - ACCESS_KEY_ID
# - ACCESS_KEY_SECRET
# - BUCKET_NAME
