name: "Set up Node and install dependencies"
description: "Sets up Node version and installs dependencies."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
    - uses: actions/cache@v2
      id: cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json', '**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
    - name: Post install
      shell: bash
      if: steps.cache.outputs.cache-hit == 'true'
      run: yarn postinstall
