name: "Set up Node and install dependencies"
description: "Sets up Node version and installs dependencies."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: "yarn"
    - name: Install Dependencies
      shell: bash
      env:
        NODE_ENV: development
        YARN_ENABLE_NETWORK: "false"
      run: yarn install --immutable --immutable-cache
