name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: yarn workspace @chealt/chealt.com build
        env:
          CI: true
      - name: Bundle size check
        run: yarn workspace @chealt/chealt.com check:bundlesize
