name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [scripts, styles]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Lint ${{ matrix.type }}
        run: yarn run lint:${{ matrix.type }}
        env:
          CI: true
