name: Outdated dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/install
    - name: Run outdated dependency check
      run: yarn outdated
