name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/install
    - name: Test
      run: yarn test
      env:
        CI: true
    - name: Store screenshots
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: packages/jest-puppeteer-env-example/screenshots
