name: UI Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
env:
  SHA: ${{ github.GITHUB_SHA || github.event.pull_request.head.sha }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Get Playwright version
        id: playwright_version
        shell: bash
        run: |
          version=$(yarn info @playwright/test --json | jq -r '.children.Version')
          echo "version=$version" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Cache Playwright
        id: cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-chromium-${{ steps.playwright_version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-chromium-
      - name: Install Playwright Browsers
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps chromium
      - name: Run Playwright tests
        run: yarn playwright test --project chromium
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: always()
        with:
          role-to-assume: arn:aws:iam::469712753210:role/chealt-github-role
          aws-region: us-east-1
      - name: Upload files to AWS
        id: report-upload
        if: always()
        run: |
          aws s3 sync playwright-report/ s3://chealt-playwright-reports/${{ env.SHA }}
      - name: Report test report upload status
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/check-runs \
              -d '{"name":"UI Tests / report","head_sha":"${{ env.SHA }}","status":"${{ steps.report-upload.status }}","details_url":"https://chealt-playwright-reports.s3.amazonaws.com/${{ env.SHA }}/index.html"}'
